version: '3.8'

x-database-name: &database-name
  DB_NAME: DevOps
x-database-port: &database-port
  DB_PORT: 27017
x-database-host-name: &database-host-name
  DB_NAME: mongo
x-database-user: &database-user
  DB_NAME: MyUser
x-database-password: &database-password
  DB_NAME: MyPassword

services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile
      args:
        << : *database-port
        << : *database-host-name
        << : *database-name
    volumes:
      - ./api:/api
    networks:
      - internal
      - external
    restart: always
    depends_on:
      - db
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${database-user}
      - MONGO_INITDB_ROOT_PASSWORD=${database-password}
      - MONGO_INITDB_DATABASE=${database-name}
    networks:
      - internal
    restart: always
    volumes:
      - data_volume:/var/lib/data
volumes:
  data_volume:

networks:
  internal:
    driver: bridge
  external:
    driver: overlay
