version: '3.8'

services:
  apigateway:
    build:
      context: ./apigateway
      dockerfile: dockerfile
    volumes:
      - ./apigateway:/apigateway
    ports:
      - 3000:3000
    restart: always
  hostingservice:
    build:
      context: ./hostingservice
      dockerfile: dockerfile
      args:
        PORT: 3001
        DB_PORT: 27017
        DB_NAME: hosting
        DB_USER: username
        DB_PASSWORD: password
    volumes:
      - ./hostingservice:/hostingservice
    ports:
      - 3001:3001
    restart: always
    depends_on:
      - hostingdb
  participationservice:
    build:
      context: ./participationservice
      dockerfile: dockerfile
      args:
        PORT: 3002
        DB_PORT: 27018
        DB_NAME: hosting
        DB_USER: username
        DB_PASSWORD: password
    volumes:
      - ./participationservice:/participationservice
    ports:
      - 3002:3002
    restart: always
    depends_on:
      - participationdb
  scoringservice:
    build:
      context: ./scoringservice
      dockerfile: dockerfile
      args:
        PORT: 3003
    volumes:
      - ./scoringservice:/scoringservice
    ports:
      - 3003:3003
    restart: always
  hostingdb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=hosting
    ports:
      - 27017:27017
    restart: always
    volumes:
      - hostingdb_volume:/data/hosting
  participationdb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=participation
    ports:
      - 27018:27017
    restart: always
    volumes:
      - participationdb_volume:/data/participation
  # db-exporter:
  #   image: bitnami/mongodb-exporter:latest
  #   command: --mongodb.uri=mongodb://username:password@mongo:27017
  #   depends_on:
  #     - mongo
  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #     - prometheus-data:/prometheus
  #   ports:
  #     - 9090:9090
  #   command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  #   depends_on:
  #     - db-exporter
  #     - api
  # grafana:
  #   build: ./grafana
  #   ports:
  #     - 3001:3001
  #   environment:
  #     - GF_SERVER_HTTP_PORT=3001
  #   depends_on:
  #     - prometheus
volumes:
  hostingdb_volume:
  participationdb_volume:
  # prometheus-data:
