version: '3.8'

services:
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: dockerfile
      args:
        API_PORT: 3000
        DB_PORT: 27017
        DB_HOST_NAME: mongo
        DB_NAME: DevOps
        DB_USER: username
        DB_PASSWORD: password
    volumes:
      - ./api_gateway:/api_gateway
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=DevOps
    ports:
      - 27017:27017
    restart: always
    volumes:
      - data_volume:/data/db
  # db-exporter:
  #   image: bitnami/mongodb-exporter:latest
  #   command: --mongodb.uri=mongodb://username:password@mongo:27017
  #   depends_on:
  #     - mongo
  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #     - prometheus-data:/prometheus
  #   ports:
  #     - 9090:9090
  #   command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  #   depends_on:
  #     - db-exporter
  #     - api
  # grafana:
  #   build: ./grafana
  #   ports:
  #     - 3001:3001
  #   environment:
  #     - GF_SERVER_HTTP_PORT=3001
  #   depends_on:
  #     - prometheus
volumes:
  data_volume:
  # prometheus-data:
