global:
  scrape_interval: 60s
  evaluation_interval: 60s
  scrape_timeout: 60s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["api:3000"]
  - job_name: "mongo"
    static_configs:
      - targets: ["db-exporter:9216"]