global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 2s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "userservice"
    static_configs:
      - targets: ["userservice:3002"]
  - job_name: "authenticationservice"
    static_configs:
      - targets: ["authenticationservice:3001"]
  - job_name: "scoringrpc"
    static_configs:
      - targets: ["scoringrpc:3003"]
  - job_name: "userdb"
    static_configs:
      - targets: ["db-exporter:9216"]