name: Continuous Integration
on:
  push:
    branches:
      - 'api/**'
  pull_request:
    branches:
      - main

jobs:
  call-workflow-code-coverage:
    uses: ./.github/workflows/Code-Coverage.yml