name: Continuous Integration
on:
  push:
    branches:
      - 'feature-**'
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: ./api
jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Check out repository
      - uses: ArtiomTr/jest-coverage-report-action@v2
        name: Run tests
        with:
          working-directory: ./api
          test-script: npm test
  es_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Check out repository
      - name: run ESLint
        run: npx eslint .
  generate_okteto_preview:
    runs-on: ubuntu-latest
    steps:
    - name: Context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Deploy preview environment
      uses: okteto/deploy-preview@latest
      env:
       GITHUB_TOKEN: ${{ secrets.OKTETO_TOKEN }}
      with:
        name: pr-${{ github.event.number }}-preview
        timeout: 15m
  destroy_okteto_preview:
    runs-on: ubuntu-latest
    steps:
    - name: Context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Destroy preview environment
      uses: okteto/destroy-preview@latest
      with:
        name: pr-${{ github.event.number }}-preview