name: Continuous Integration
on:
  push:
    branches:
      - 'api/**'
  pull_request:
    branches:
      - main
jobs:
  call-workflow-code-coverage:
    uses: avans-devops/devops-2122-merijnmonfils_ryanwennekes/.github/workflows/Code-Coverage.yml@main