name: Continuous Integration
on:
  push:
    branches:
      - 'feature-**'
  pull_request:
    branches:
      - main
    
jobs:
  auth-service:
    uses: ./.github/workflows/Auth_CI.yml
  user-service:
    uses: ./.github/workflows/User_CI.yml
  scoring-rpc-server:
    uses: ./.github/workflows/Scoring_CI.yml