name: Continuous Integration
on:
  push:
    branches:
      - 'feature-**'
  pull_request:
    branches:
      - main
    
jobs:
  auth-service:
    uses: ./.github/workflows/authenticationservice/CI.yml
  user-service:
    uses: ./.github/workflows/userservice/CI.yml
  scoring-rpc-server:
    uses: ./.github/workflows/scoringrpcserver/CI.yml