name: Continuous Integration
on:
  push:
    branches:
      - 'feature-**'
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: ./apigateway
jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Check out repository
      - run: npm install

      - name: NYC Coverage Report
          uses: Tintef/nyc-reporter-action@0.1.0
        with:
          coverage-command: "nyc --reporter=text mocha ./**/test/*test.js"
          token: ${{ secrets.GITHUB_TOKEN }}
  es_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Check out repository
      - name: run ESLint
        run: npx eslint .