name: Continuous Integration
on:
  push:
    branches:
      - 'feature-**'
  pull_request:
    branches:
      - main
    
jobs:
  es_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Check out repository
      - name: run ESLint
        run: npx eslint .
  auth_service_code_coverage:
    defaults:
      run:
        working-directory: authenticationservice
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Check out repository
      - run: npm install

      - name: Run Mocha Tests
        run: npm run coverage

      - name: Generate NYC report
        run: |
          npx nyc report \
            --reporter json-summary \
            --report-dir nyc-coverage-report \
            --exclude-after-remap false

      - name: Report NYC coverage
        uses: sidx1024/report-nyc-coverage-github-action@v1.1
        with:
          sources_base_path: ${{ format('{0}/authenticationservice', github.workspace) }}
          coverage_file: "nyc-coverage-report/coverage-summary.json"
          github_token: ${{ secrets.GITHUB_TOKEN }}
  user_service_code_coverage:
    defaults:
      run:
        working-directory: ./userservice
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Check out repository
      - run: npm install

      - name: Run Mocha Tests
        run: npm test

      - name: NYC Coverage Report
        uses: Tintef/nyc-reporter-action@0.1.0
        with:
          coverage-command: "nyc --reporter=text mocha ./test/*test.js"
          token: ${{ secrets.GITHUB_TOKEN }}
  scoring_rpc_server_code_coverage:
    defaults:
      run:
        working-directory: ./scoringrpc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Check out repository
      - run: npm install

      - name: Run Mocha Tests
        run: npm test

      - name: NYC Coverage Report
        uses: Tintef/nyc-reporter-action@0.1.0
        with:
          coverage-command: "nyc --reporter=text mocha ./test/*test.js"
          token: ${{ secrets.GITHUB_TOKEN }}