name: Continuous Integration
on:
  push:
    branches:
      - 'feature-**'
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: ./apigateway
jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Check out repository
      - run: npm install

      - name: Run tests
        run: npm run test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Mocha Tests            # Name of the check run which will be created
          path: reports/mocha-*.xml    # Path to test results
          reporter: mocha-json
  es_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Check out repository
      - name: run ESLint
        run: npx eslint .