name: Test Code Coverage
on:
  workflow_call:
defaults:
  run:
    working-directory: ./api
jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Check out repository
      - uses: ArtiomTr/jest-coverage-report-action@v2
        name: Run tests
        with:
          working-directory: ./api