name: Test Code Coverage

on:
  workflow_call:

defaults:
  run:
    working-directory: ./api

jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./api